# whether the path/traj is predefined
predefined: true

# trajtype
TrajType: LEMNISCATE_TRAJ # CIRCLE_TRAJ, BLOCK_TRAJ, LEMNISCATE_TRAJ

# center
x0: 0.0
y0: 0.4
z0: 1.2

# misc
pub_freq: 100
lap_no: 4
ccw: true

# z move or not
z_moving: false
z_moving_amp: 0.4
z_moving_perioud: 7.5

# circle
circle_velo: 12.0 # dg/s
circle_radius: 1.6

# block
block_velo: 0.4 # m/s
block_length: 2
block_AR: 1
block_T_angle: 0.0

# lemniscate
amp: 1.4
lemi_velo: 60.0 # dg/s
timePerLap: 2.0


starting_error: 0.8
